export type EdgeFunctionInfo = {
  name: string;
  category: string;
  accent: "cyan" | "emerald" | "orange" | "violet" | "blue" | "rose" | "amber";
  triggers: ("manual" | "cron" | "webhook")[];
};

export const EDGE_FUNCTIONS: EdgeFunctionInfo[] = [
  { name: "ad-director-ai", category: "Agents / Chat", accent: "cyan", triggers: ["manual"] },
  { name: "admin-chat", category: "Agents / Chat", accent: "cyan", triggers: ["manual"] },
  { name: "agent-router", category: "Agents / Chat", accent: "cyan", triggers: ["manual"] },
  { name: "ai-agent", category: "AI / LLM", accent: "cyan", triggers: ["manual"] },
  { name: "ai-document-import", category: "AI / LLM", accent: "cyan", triggers: ["manual"] },
  { name: "ai-estimate", category: "AI / LLM", accent: "cyan", triggers: ["manual"] },
  { name: "ai-generate-quotation", category: "AI / LLM", accent: "cyan", triggers: ["manual"] },
  { name: "ai-generic", category: "AI / LLM", accent: "cyan", triggers: ["manual"] },
  { name: "ai-health", category: "AI / LLM", accent: "cyan", triggers: ["manual"] },
  { name: "ai-health-cron", category: "AI / LLM", accent: "cyan", triggers: ["cron"] },
  { name: "ai-inline-suggest", category: "AI / LLM", accent: "cyan", triggers: ["manual"] },
  { name: "ai-media-suggestions", category: "AI / LLM", accent: "cyan", triggers: ["manual"] },
  { name: "alert-router", category: "Communications", accent: "rose", triggers: ["manual"] },
  { name: "analyze-ad-script", category: "AI / LLM", accent: "cyan", triggers: ["manual"] },
  { name: "analyze-feedback-fix", category: "AI / LLM", accent: "cyan", triggers: ["manual"] },
  { name: "analyze-scope", category: "AI / LLM", accent: "cyan", triggers: ["manual"] },
  { name: "app-help-chat", category: "Agents / Chat", accent: "cyan", triggers: ["manual"] },
  { name: "approval-notify", category: "Communications", accent: "rose", triggers: ["manual"] },
  { name: "ar-aging-escalation", category: "General", accent: "amber", triggers: ["cron"] },
  { name: "archive-odoo-files", category: "General", accent: "amber", triggers: ["manual"] },
  { name: "assistant-action", category: "Agents / Chat", accent: "cyan", triggers: ["manual"] },
  { name: "auto-approve-penny", category: "Autopilot", accent: "rose", triggers: ["cron"] },
  { name: "auto-generate-post", category: "Social", accent: "orange", triggers: ["manual"] },
  { name: "auto-reconcile", category: "General", accent: "amber", triggers: ["manual"] },
  { name: "autopilot-engine", category: "Autopilot", accent: "rose", triggers: ["cron"] },
  { name: "build-learning-pairs", category: "ERP Core", accent: "blue", triggers: ["manual"] },
  { name: "camera-events", category: "Vision / Media", accent: "amber", triggers: ["webhook"] },
  { name: "camera-ping", category: "Vision / Media", accent: "amber", triggers: ["webhook"] },
  { name: "check-escalations", category: "General", accent: "amber", triggers: ["cron"] },
  { name: "check-sla-breaches", category: "General", accent: "amber", triggers: ["cron"] },
  { name: "comms-alerts", category: "Communications", accent: "rose", triggers: ["cron"] },
  { name: "consume-invite", category: "General", accent: "amber", triggers: ["manual"] },
  { name: "convert-quote-to-order", category: "ERP Core", accent: "blue", triggers: ["manual"] },
  { name: "daily-summary", category: "Communications", accent: "rose", triggers: ["cron", "manual"] },
  { name: "daily-team-report", category: "Communications", accent: "rose", triggers: ["cron"] },
  { name: "diagnostic-logs", category: "General", accent: "amber", triggers: ["manual"] },
  { name: "draft-email", category: "Communications", accent: "rose", triggers: ["manual"] },
  { name: "edit-video-prompt", category: "AI / LLM", accent: "cyan", triggers: ["manual"] },
  { name: "eisenhower-team-report", category: "Communications", accent: "rose", triggers: ["cron", "manual"] },
  { name: "elevenlabs-azin-token", category: "Voice / Audio", accent: "violet", triggers: ["manual"] },
  { name: "elevenlabs-conversation-token", category: "Voice / Audio", accent: "violet", triggers: ["manual"] },
  { name: "elevenlabs-music", category: "Voice / Audio", accent: "violet", triggers: ["manual"] },
  { name: "elevenlabs-scribe-token", category: "Voice / Audio", accent: "violet", triggers: ["manual"] },
  { name: "elevenlabs-transcribe", category: "Voice / Audio", accent: "violet", triggers: ["manual"] },
  { name: "elevenlabs-tts", category: "Voice / Audio", accent: "violet", triggers: ["manual"] },
  { name: "email-activity-report", category: "Communications", accent: "rose", triggers: ["cron"] },
  { name: "email-analytics", category: "Communications", accent: "rose", triggers: ["manual"] },
  { name: "email-automation-check", category: "Communications", accent: "rose", triggers: ["cron"] },
  { name: "email-campaign-generate", category: "Communications", accent: "rose", triggers: ["manual"] },
  { name: "email-campaign-send", category: "Communications", accent: "rose", triggers: ["manual"] },
  { name: "email-unsubscribe", category: "Communications", accent: "rose", triggers: ["webhook"] },
  { name: "embed-documents", category: "ERP Core", accent: "blue", triggers: ["manual"] },
  { name: "empire-architect", category: "Autopilot", accent: "rose", triggers: ["manual"] },
  { name: "enhance-music-prompt", category: "AI / LLM", accent: "cyan", triggers: ["manual"] },
  { name: "extract-manifest", category: "ERP Core", accent: "blue", triggers: ["manual"] },
  { name: "face-recognize", category: "Face Recognition", accent: "rose", triggers: ["manual"] },
  { name: "face-recover-orphans", category: "Face Recognition", accent: "rose", triggers: ["cron"] },
  { name: "facebook-data-deletion", category: "OAuth / Integrations", accent: "amber", triggers: ["webhook"] },
  { name: "facebook-oauth", category: "OAuth / Integrations", accent: "amber", triggers: ["manual"] },
  { name: "firecrawl-scrape", category: "SEO", accent: "emerald", triggers: ["manual"] },
  { name: "friday-ideas", category: "Communications", accent: "rose", triggers: ["cron"] },
  { name: "gce-video-assembly", category: "Vision / Media", accent: "amber", triggers: ["manual"] },
  { name: "generate-daily-report-pdf", category: "ERP Core", accent: "blue", triggers: ["manual"] },
  { name: "generate-fix-prompt", category: "AI / LLM", accent: "cyan", triggers: ["manual"] },
  { name: "generate-image", category: "Vision / Media", accent: "amber", triggers: ["manual"] },
  { name: "generate-invoice-pdf", category: "ERP Core", accent: "blue", triggers: ["manual"] },
  { name: "generate-suggestions", category: "AI / LLM", accent: "cyan", triggers: ["manual"] },
  { name: "generate-thumbnail", category: "Vision / Media", accent: "amber", triggers: ["manual"] },
  { name: "generate-vapid-keys", category: "General", accent: "amber", triggers: ["manual"] },
  { name: "generate-video", category: "Vision / Media", accent: "amber", triggers: ["manual"] },
  { name: "get-vapid-public-key", category: "General", accent: "amber", triggers: ["manual"] },
  { name: "gmail-attachment", category: "Gmail", accent: "rose", triggers: ["manual"] },
  { name: "gmail-delete", category: "Gmail", accent: "rose", triggers: ["manual"] },
  { name: "gmail-send", category: "Gmail", accent: "rose", triggers: ["manual"] },
  { name: "gmail-sync", category: "Gmail", accent: "rose", triggers: ["manual"] },
  { name: "gmail-webhook", category: "Gmail", accent: "rose", triggers: ["webhook"] },
  { name: "google-oauth", category: "OAuth / Integrations", accent: "amber", triggers: ["manual"] },
  { name: "google-vision-ocr", category: "Vision / Media", accent: "amber", triggers: ["manual"] },
  { name: "grammar-check", category: "AI / LLM", accent: "cyan", triggers: ["manual"] },
  { name: "handle-command", category: "Agents / Chat", accent: "cyan", triggers: ["manual"] },
  { name: "import-crm-data", category: "General", accent: "amber", triggers: ["manual"] },
  { name: "ingest-historical-barlists", category: "ERP Core", accent: "blue", triggers: ["manual"] },
  { name: "ingest-job-logs", category: "ERP Core", accent: "blue", triggers: ["manual"] },
  { name: "ingest-shop-drawings", category: "ERP Core", accent: "blue", triggers: ["manual"] },
  { name: "kiosk-punch", category: "ERP Core", accent: "blue", triggers: ["manual"] },
  { name: "linkedin-oauth", category: "OAuth / Integrations", accent: "amber", triggers: ["manual"] },
  { name: "log-machine-run", category: "ERP Core", accent: "blue", triggers: ["manual"] },
  { name: "lyria-music", category: "Voice / Audio", accent: "violet", triggers: ["manual"] },
  { name: "manage-bend", category: "ERP Core", accent: "blue", triggers: ["manual"] },
  { name: "manage-extract", category: "ERP Core", accent: "blue", triggers: ["manual"] },
  { name: "manage-inventory", category: "ERP Core", accent: "blue", triggers: ["manual"] },
  { name: "manage-machine", category: "ERP Core", accent: "blue", triggers: ["manual"] },
  { name: "mcp-server", category: "General", accent: "amber", triggers: ["manual"] },
  { name: "meeting-live-notes", category: "Communications", accent: "rose", triggers: ["manual"] },
  { name: "notify-feedback-owner", category: "Communications", accent: "rose", triggers: ["manual"] },
  { name: "notify-lead-assignees", category: "Communications", accent: "rose", triggers: ["manual"] },
  { name: "notify-on-message", category: "Communications", accent: "rose", triggers: ["manual"] },
  { name: "odoo-chatter-sync", category: "Odoo", accent: "amber", triggers: ["manual"] },
  { name: "odoo-crm-sync", category: "Odoo", accent: "amber", triggers: ["manual"] },
  { name: "odoo-file-proxy", category: "Odoo", accent: "amber", triggers: ["manual"] },
  { name: "odoo-reconciliation-report", category: "Odoo", accent: "amber", triggers: ["manual"] },
  { name: "odoo-sync-order-lines", category: "Odoo", accent: "amber", triggers: ["manual"] },
  { name: "payroll-engine", category: "ERP Core", accent: "blue", triggers: ["manual"] },
  { name: "pdf-to-images", category: "Vision / Media", accent: "amber", triggers: ["manual"] },
  { name: "penny-auto-actions", category: "Autopilot", accent: "rose", triggers: ["manual"] },
  { name: "penny-execute-action", category: "Autopilot", accent: "rose", triggers: ["manual"] },
  { name: "personaplex-voice", category: "Voice / Audio", accent: "violet", triggers: ["manual"] },
  { name: "pexels-search", category: "Social", accent: "orange", triggers: ["manual"] },
  { name: "pipeline-ai", category: "Pipeline / Sales", accent: "emerald", triggers: ["manual"] },
  { name: "pipeline-automation-engine", category: "Pipeline / Sales", accent: "emerald", triggers: ["cron"] },
  { name: "pipeline-digest", category: "Pipeline / Sales", accent: "emerald", triggers: ["cron"] },
  { name: "pipeline-lead-recycler", category: "Pipeline / Sales", accent: "emerald", triggers: ["cron"] },
  { name: "pipeline-webhooks", category: "Pipeline / Sales", accent: "emerald", triggers: ["webhook"] },
  { name: "plaid-bank", category: "Banking", accent: "blue", triggers: ["webhook"] },
  { name: "process-rfq-emails", category: "Pipeline / Sales", accent: "emerald", triggers: ["manual"] },
  { name: "prospect-leads", category: "Pipeline / Sales", accent: "emerald", triggers: ["manual"] },
  { name: "push-on-notify", category: "Communications", accent: "rose", triggers: ["manual"] },
  { name: "qa-war-engine", category: "Autopilot", accent: "rose", triggers: ["manual"] },
  { name: "qb-audit", category: "QuickBooks", accent: "blue", triggers: ["cron", "manual"] },
  { name: "qb-sync-engine", category: "QuickBooks", accent: "blue", triggers: ["manual"] },
  { name: "qb-webhook", category: "QuickBooks", accent: "blue", triggers: ["webhook"] },
  { name: "quickbooks-oauth", category: "QuickBooks", accent: "blue", triggers: ["manual"] },
  { name: "quote-engine", category: "ERP Core", accent: "blue", triggers: ["manual"] },
  { name: "quote-expiry-watchdog", category: "ERP Core", accent: "blue", triggers: ["cron"] },
  { name: "quote-public-view", category: "ERP Core", accent: "blue", triggers: ["manual"] },
  { name: "regenerate-post", category: "Social", accent: "orange", triggers: ["manual"] },
  { name: "relay-pipeline", category: "General", accent: "amber", triggers: ["manual"] },
  { name: "relink-orphan-invoices", category: "General", accent: "amber", triggers: ["manual"] },
  { name: "ringcentral-action", category: "RingCentral", accent: "orange", triggers: ["manual"] },
  { name: "ringcentral-active-calls", category: "RingCentral", accent: "orange", triggers: ["manual"] },
  { name: "ringcentral-ai", category: "RingCentral", accent: "orange", triggers: ["manual"] },
  { name: "ringcentral-call-analytics", category: "RingCentral", accent: "orange", triggers: ["manual"] },
  { name: "ringcentral-fax-send", category: "RingCentral", accent: "orange", triggers: ["manual"] },
  { name: "ringcentral-oauth", category: "RingCentral", accent: "orange", triggers: ["manual"] },
  { name: "ringcentral-presence", category: "RingCentral", accent: "orange", triggers: ["manual"] },
  { name: "ringcentral-recording", category: "RingCentral", accent: "orange", triggers: ["manual"] },
  { name: "ringcentral-register-webhook", category: "RingCentral", accent: "orange", triggers: ["webhook"] },
  { name: "ringcentral-sip-provision", category: "RingCentral", accent: "orange", triggers: ["manual"] },
  { name: "ringcentral-sync", category: "RingCentral", accent: "orange", triggers: ["manual"] },
  { name: "ringcentral-video", category: "RingCentral", accent: "orange", triggers: ["manual"] },
  { name: "ringcentral-webhook", category: "RingCentral", accent: "orange", triggers: ["webhook"] },
  { name: "sales-concierge", category: "Agents / Chat", accent: "cyan", triggers: ["manual"] },
  { name: "schedule-post", category: "Social", accent: "orange", triggers: ["manual"] },
  { name: "search-embeddings", category: "ERP Core", accent: "blue", triggers: ["manual"] },
  { name: "semrush-api", category: "SEO", accent: "emerald", triggers: ["manual"] },
  { name: "send-push", category: "Communications", accent: "rose", triggers: ["manual"] },
  { name: "send-quote-email", category: "Communications", accent: "rose", triggers: ["manual"] },
  { name: "seo-ai-analyze", category: "SEO", accent: "emerald", triggers: ["manual"] },
  { name: "seo-ai-copilot", category: "SEO", accent: "emerald", triggers: ["manual"] },
  { name: "seo-ai-strategy", category: "SEO", accent: "emerald", triggers: ["manual"] },
  { name: "seo-ai-visibility-audit", category: "SEO", accent: "emerald", triggers: ["manual"] },
  { name: "seo-email-harvest", category: "SEO", accent: "emerald", triggers: ["manual"] },
  { name: "seo-gsc-sync", category: "SEO", accent: "emerald", triggers: ["cron", "manual"] },
  { name: "seo-keyword-harvest", category: "SEO", accent: "emerald", triggers: ["manual"] },
  { name: "seo-link-audit", category: "SEO", accent: "emerald", triggers: ["manual"] },
  { name: "seo-local-audit", category: "SEO", accent: "emerald", triggers: ["manual"] },
  { name: "seo-rank-check", category: "SEO", accent: "emerald", triggers: ["cron"] },
  { name: "seo-semrush-import", category: "SEO", accent: "emerald", triggers: ["manual"] },
  { name: "seo-site-crawl", category: "SEO", accent: "emerald", triggers: ["cron"] },
  { name: "seo-smart-scan", category: "SEO", accent: "emerald", triggers: ["manual"] },
  { name: "seo-task-execute", category: "SEO", accent: "emerald", triggers: ["manual"] },
  { name: "shape-vision", category: "Vision / Media", accent: "amber", triggers: ["manual"] },
  { name: "smart-dispatch", category: "Autopilot", accent: "rose", triggers: ["manual"] },
  { name: "smoke-tests", category: "General", accent: "amber", triggers: ["cron"] },
  { name: "social-cron-publish", category: "Social", accent: "orange", triggers: ["cron"] },
  { name: "social-intelligence", category: "Social", accent: "orange", triggers: ["manual"] },
  { name: "social-publish", category: "Social", accent: "orange", triggers: ["manual"] },
  { name: "stripe-payment", category: "Stripe", accent: "violet", triggers: ["manual"] },
  { name: "stripe-qb-webhook", category: "QuickBooks", accent: "blue", triggers: ["webhook"] },
  { name: "summarize-call", category: "Communications", accent: "rose", triggers: ["manual"] },
  { name: "summarize-meeting", category: "Communications", accent: "rose", triggers: ["manual"] },
  { name: "support-chat", category: "Agents / Chat", accent: "cyan", triggers: ["manual"] },
  { name: "support-suggest", category: "Agents / Chat", accent: "cyan", triggers: ["manual"] },
  { name: "sync-overdue-tasks", category: "General", accent: "amber", triggers: ["cron", "manual"] },
  { name: "synology-proxy", category: "OAuth / Integrations", accent: "amber", triggers: ["manual"] },
  { name: "system-backup", category: "General", accent: "amber", triggers: ["manual"] },
  { name: "tiktok-oauth", category: "OAuth / Integrations", accent: "amber", triggers: ["manual"] },
  { name: "timeclock-alerts", category: "Communications", accent: "rose", triggers: ["cron"] },
  { name: "transcribe-translate", category: "Voice / Audio", accent: "violet", triggers: ["manual"] },
  { name: "transform-video-prompt", category: "AI / LLM", accent: "cyan", triggers: ["manual"] },
  { name: "translate-caption", category: "Social", accent: "orange", triggers: ["manual"] },
  { name: "translate-message", category: "Communications", accent: "rose", triggers: ["manual"] },
  { name: "translate-notification", category: "Communications", accent: "rose", triggers: ["manual"] },
  { name: "validate-clearance-photo", category: "Vision / Media", accent: "amber", triggers: ["manual"] },
  { name: "validate-invite", category: "General", accent: "amber", triggers: ["manual"] },
  { name: "video-intelligence", category: "Vision / Media", accent: "amber", triggers: ["manual"] },
  { name: "video-to-social", category: "Social", accent: "orange", triggers: ["manual"] },
  { name: "vizzy-agent-audit", category: "Vizzy AI", accent: "violet", triggers: ["manual"] },
  { name: "vizzy-briefing", category: "Vizzy AI", accent: "violet", triggers: ["manual"] },
  { name: "vizzy-business-watchdog", category: "Vizzy AI", accent: "violet", triggers: ["cron"] },
  { name: "vizzy-call-receptionist", category: "Vizzy AI", accent: "violet", triggers: ["manual"] },
  { name: "vizzy-context", category: "Vizzy AI", accent: "violet", triggers: ["manual"] },
  { name: "vizzy-daily-brief", category: "Vizzy AI", accent: "violet", triggers: ["cron"] },
  { name: "vizzy-erp-action", category: "Vizzy AI", accent: "violet", triggers: ["manual"] },
  { name: "vizzy-glasses-webhook", category: "Vizzy AI", accent: "violet", triggers: ["webhook"] },
  { name: "vizzy-photo-analyze", category: "Vizzy AI", accent: "violet", triggers: ["manual"] },
  { name: "vizzy-pre-digest", category: "Vizzy AI", accent: "violet", triggers: ["cron"] },
  { name: "vizzy-sms-reply", category: "Vizzy AI", accent: "violet", triggers: ["webhook"] },
  { name: "vizzy-tts", category: "Vizzy AI", accent: "violet", triggers: ["manual"] },
  { name: "vizzy-voice", category: "Vizzy AI", accent: "violet", triggers: ["manual"] },
  { name: "vizzy-voice-chat", category: "Vizzy AI", accent: "violet", triggers: ["manual"] },
  { name: "vizzy-web-research", category: "Vizzy AI", accent: "violet", triggers: ["manual"] },
  { name: "voice-engine-token", category: "Voice / Audio", accent: "violet", triggers: ["manual"] },
  { name: "wc-webhook", category: "General", accent: "amber", triggers: ["webhook"] },
  { name: "website-agent", category: "Website", accent: "cyan", triggers: ["manual"] },
  { name: "website-chat", category: "Website", accent: "cyan", triggers: ["manual"] },
  { name: "website-chat-widget", category: "Website", accent: "cyan", triggers: ["manual"] },
  { name: "website-health-check", category: "Website", accent: "cyan", triggers: ["cron"] },
  { name: "website-speed-audit", category: "Website", accent: "cyan", triggers: ["manual"] },
  { name: "wincher-import", category: "SEO", accent: "emerald", triggers: ["manual"] },
  { name: "wincher-sync", category: "SEO", accent: "emerald", triggers: ["cron", "manual"] },
  { name: "wp-fix-hero", category: "Website", accent: "cyan", triggers: ["manual"] },
  { name: "wp-speed-optimizer", category: "Website", accent: "cyan", triggers: ["manual"] },
  { name: "wp-test", category: "Website", accent: "cyan", triggers: ["manual"] },
];

export const EDGE_FUNCTION_CATEGORIES = Array.from(new Set(EDGE_FUNCTIONS.map((f) => f.category))).sort();
