import { handleRequest } from "../_shared/requestHandler.ts";
import { corsHeaders } from "../_shared/auth.ts";

import {
  generateQuote,
  validateEstimateRequest,
  generateExplanation,
  type EstimateRequest,
  type PricingConfig,
  type RebarSizeRow,
} from "../_shared/quoteCalcEngine.ts";

Deno.serve((req) =>
  handleRequest(req, async ({ serviceClient: supabase, body }) => {
    const { action, estimate_request, company_id } = body as {
      action: "validate" | "quote" | "explain";
      estimate_request: EstimateRequest;
      company_id: string;
    };

    if (!action || !estimate_request) {
      return new Response(
        JSON.stringify({ error: "Missing action or estimate_request" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Load pricing config
    const { data: configRow, error: configErr } = await supabase
      .from("quote_pricing_configs")
      .select("pricing_data")
      .eq("company_id", company_id)
      .eq("is_active", true)
      .order("created_at", { ascending: false })
      .limit(1)
      .maybeSingle();

    if (configErr || !configRow) {
      return new Response(
        JSON.stringify({
          error: "No active pricing config found for this company.",
          details: configErr?.message,
        }),
        { status: 404, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const config = configRow.pricing_data as unknown as PricingConfig;

    // Load rebar sizes
    const { data: rebarSizes, error: rebarErr } = await supabase
      .from("rebar_sizes")
      .select("bar_code, mass_kg_per_m, diameter_mm");

    if (rebarErr || !rebarSizes) {
      return new Response(
        JSON.stringify({ error: "Failed to load rebar sizes.", details: rebarErr?.message }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // ─── VALIDATE ───
    if (action === "validate") {
      const questions = validateEstimateRequest(estimate_request, config);
      return {
        valid: questions.length === 0,
        missing_inputs_questions: questions.length > 0 ? questions : null,
      };
    }

    // ─── QUOTE ───
    if (action === "quote") {
      const result = generateQuote(
        estimate_request,
        config,
        rebarSizes as RebarSizeRow[]
      );

      // ─── $0 QUOTE GUARD ───
      if (result.summary.grand_total <= 0 && result.line_items.length > 0) {
        return new Response(
          JSON.stringify({
            error: "Pricing resulted in $0 total despite having line items. This is a pricing failure, not a valid quote.",
            pricing_status: "failed",
            failure_reason: "grand_total_zero",
            failure_details: {
              line_items_count: result.line_items.length,
              subtotal: result.summary.subtotal,
              grand_total: result.summary.grand_total,
              missing_inputs: result.missing_inputs_questions,
              weights: result.weights_summary,
            },
            result,
          }),
          { status: 422, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      // Persist to quotes table
      const quoteNumber = `QE-${Date.now().toString(36).toUpperCase()}`;
      try {
        const { data: quoteRow, error: insertErr } = await supabase
          .from("quotes")
          .insert({
            quote_number: quoteNumber,
            company_id,
            total_amount: result.summary.grand_total,
            source: "quote_engine",
            status: result.summary.grand_total > 0 ? "draft" : "pricing_failed",
            metadata: {
              estimate_request,
              result,
            },
            notes: `Generated by Quote Engine for ${estimate_request.project.project_name}`,
          })
          .select("id")
          .single();

        if (!insertErr && quoteRow) {
          result.quote_id = quoteRow.id;
        }
      } catch (e) {
        console.error("Failed to persist quote:", e);
      }

      return result;
    }

    // ─── EXPLAIN ───
    if (action === "explain") {
      const result = generateQuote(
        estimate_request,
        config,
        rebarSizes as RebarSizeRow[]
      );
      const explanation = generateExplanation(estimate_request, result, config);
      return { explanation, result };
    }

    return new Response(
      JSON.stringify({ error: `Unknown action: ${action}` }),
      { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }, { functionName: "quote-engine", requireCompany: false, wrapResult: false })
);
