import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import {
  generateQuote,
  validateEstimateRequest,
  generateExplanation,
  type EstimateRequest,
  type PricingConfig,
  type RebarSizeRow,
} from "../_shared/quoteCalcEngine.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
    );

    const body = await req.json();
    const { action, estimate_request, company_id } = body as {
      action: "validate" | "quote" | "explain";
      estimate_request: EstimateRequest;
      company_id: string;
    };

    if (!action || !estimate_request) {
      return new Response(
        JSON.stringify({ error: "Missing action or estimate_request" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Load pricing config
    const { data: configRow, error: configErr } = await supabase
      .from("quote_pricing_configs")
      .select("pricing_data")
      .eq("company_id", company_id)
      .eq("is_active", true)
      .order("created_at", { ascending: false })
      .limit(1)
      .maybeSingle();

    if (configErr || !configRow) {
      return new Response(
        JSON.stringify({
          error: "No active pricing config found for this company.",
          details: configErr?.message,
        }),
        { status: 404, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const config = configRow.pricing_data as unknown as PricingConfig;

    // Load rebar sizes
    const { data: rebarSizes, error: rebarErr } = await supabase
      .from("rebar_sizes")
      .select("bar_code, mass_kg_per_m, diameter_mm");

    if (rebarErr || !rebarSizes) {
      return new Response(
        JSON.stringify({ error: "Failed to load rebar sizes.", details: rebarErr?.message }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // ─── VALIDATE ───
    if (action === "validate") {
      const questions = validateEstimateRequest(estimate_request, config);
      return new Response(
        JSON.stringify({
          valid: questions.length === 0,
          missing_inputs_questions: questions.length > 0 ? questions : null,
        }),
        { headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // ─── QUOTE ───
    if (action === "quote") {
      const result = generateQuote(
        estimate_request,
        config,
        rebarSizes as RebarSizeRow[]
      );

      // Persist to quotes table
      const quoteNumber = `QE-${Date.now().toString(36).toUpperCase()}`;
      try {
        const { data: quoteRow, error: insertErr } = await supabase
          .from("quotes")
          .insert({
            quote_number: quoteNumber,
            company_id,
            total_amount: result.summary.grand_total,
            source: "quote_engine",
            status: "draft",
            metadata: {
              estimate_request,
              result,
            },
            notes: `Generated by Quote Engine for ${estimate_request.project.project_name}`,
          })
          .select("id")
          .single();

        if (!insertErr && quoteRow) {
          result.quote_id = quoteRow.id;
        }
      } catch (e) {
        // Non-fatal — quote still returned
        console.error("Failed to persist quote:", e);
      }

      return new Response(JSON.stringify(result), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // ─── EXPLAIN ───
    if (action === "explain") {
      // First generate the quote to explain
      const result = generateQuote(
        estimate_request,
        config,
        rebarSizes as RebarSizeRow[]
      );
      const explanation = generateExplanation(estimate_request, result, config);
      return new Response(
        JSON.stringify({ explanation, result }),
        { headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    return new Response(
      JSON.stringify({ error: `Unknown action: ${action}` }),
      { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (err) {
    console.error("Quote engine error:", err);
    return new Response(
      JSON.stringify({ error: "Internal error", details: String(err) }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
