import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
import { Loader2, Languages, ListChecks, FileText, Sparkles, Eraser, MessageSquare, ClipboardList } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import { addMarkdownToPdf } from "@/lib/pdfMarkdownRenderer";


const TARGET_LANGUAGES = [
  "English", "Spanish", "French", "German", "Portuguese", "Italian", "Dutch",
  "Russian", "Chinese", "Japanese", "Korean", "Arabic", "Hindi", "Farsi",
  "Turkish", "Polish", "Vietnamese", "Thai", "Indonesian", "Malay", "Bengali",
  "Urdu", "Swahili", "Hebrew", "Greek", "Czech", "Georgian",
];

interface PostProcessToolbarProps {
  transcript: string;
  onResult: (result: string, type: string) => void;
  selectedSpeaker?: string | null;
  onFinalReport?: () => void;
  allSpeakersComplete?: boolean;
  isFinalReportLoading?: boolean;
}

async function generatePdfReport(transcript: string, summary: string, selectedSpeaker: string | null) {
  const { default: jsPDF } = await import("jspdf");
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;
  let y = margin;

  const addText = (text: string, fontSize: number, style: "normal" | "bold" = "normal", color: [number, number, number] = [30, 30, 30]) => {
    doc.setFontSize(fontSize);
    doc.setFont("helvetica", style);
    doc.setTextColor(...color);
    const lines = doc.splitTextToSize(text, maxWidth);
    for (const line of lines) {
      if (y + fontSize * 0.5 > pageHeight - 25) {
        doc.addPage();
        y = margin;
      }
      doc.text(line, margin, y);
      y += fontSize * 0.45;
    }
  };

  const addSpacer = (h = 6) => { y += h; };

  // Header
  addText("Conversation Report", 20, "bold", [20, 20, 80]);
  addSpacer(4);

  // Date
  const now = new Date();
  addText(`Date: ${now.toLocaleDateString()} — ${now.toLocaleTimeString()}`, 10, "normal", [100, 100, 100]);
  addSpacer(4);

  // Participants
  const participants = selectedSpeaker ? `${selectedSpeaker} ↔ NEEL` : "General Transcript";
  addText(`Participants: ${participants}`, 11, "bold");
  addSpacer(2);

  // Line
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageWidth - margin, y);
  addSpacer(6);

  // Transcript section
  addText("Full Transcript", 14, "bold", [20, 20, 80]);
  addSpacer(3);
  addText(transcript, 9, "normal", [50, 50, 50]);
  addSpacer(8);

  // Line
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageWidth - margin, y);
  addSpacer(6);

  // Summary section
  addText("AI Summary", 14, "bold", [20, 20, 80]);
  addSpacer(3);
  y = addMarkdownToPdf(doc, summary, { margin, maxWidth, pageHeight, startY: y });
  addSpacer(12);

  // Disclaimer
  doc.setDrawColor(220, 180, 50);
  doc.setFillColor(255, 250, 230);
  const disclaimerY = Math.min(y, pageHeight - 30);
  if (disclaimerY < margin) doc.addPage();
  const finalY = disclaimerY < margin ? margin : disclaimerY;
  doc.roundedRect(margin, finalY, maxWidth, 14, 2, 2, "FD");
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(140, 100, 0);
  doc.text(
    "This report was generated by Artificial Intelligence and may contain inaccuracies.",
    pageWidth / 2,
    finalY + 8,
    { align: "center" }
  );

  // Download
  const filename = `conversation-report-${now.toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
}

export function PostProcessToolbar({ transcript, onResult, selectedSpeaker, onFinalReport, allSpeakersComplete, isFinalReportLoading }: PostProcessToolbarProps) {
  const [processing, setProcessing] = useState<string | null>(null);
  const [customPrompt, setCustomPrompt] = useState("");
  const [targetLang, setTargetLang] = useState("English");
  const [showCustom, setShowCustom] = useState(false);

  const callPostProcess = async (postProcess: string, extra?: Record<string, string>) => {
    if (!transcript.trim()) {
      toast.error("No transcript to process");
      return;
    }
    setProcessing(postProcess);
    try {
      const { data, error } = await supabase.functions.invoke("transcribe-translate", {
        body: {
          mode: "text",
          text: transcript,
          postProcess,
          targetLang: extra?.targetLang || targetLang,
          customPrompt: extra?.customPrompt,
        },
      });
      if (error) throw new Error(error.message);
      const output = data?.result || data?.english || data?.original || JSON.stringify(data);
      onResult(output, postProcess);

      // Generate PDF for summarize
      if (postProcess === "summarize") {
        try {
          generatePdfReport(transcript, output, selectedSpeaker ?? null);
          toast.success("PDF report downloaded");
        } catch (pdfErr: any) {
          console.error("PDF generation failed", pdfErr);
          toast.error("PDF generation failed");
        }
      } else {
        toast.success(`${postProcess.replace("-", " ")} complete`);
      }
    } catch (err: any) {
      toast.error(err.message || "Processing failed");
    } finally {
      setProcessing(null);
    }
  };

  const actions = [
    { id: "translate", label: "Translate", icon: Languages },
    { id: "summarize", label: "Summarize", icon: Sparkles },
    { id: "action-items", label: "Action Items", icon: ListChecks },
    { id: "meeting-notes", label: "Meeting Notes", icon: FileText },
    { id: "cleanup", label: "Clean Up", icon: Eraser },
  ];

  return (
    <div className="space-y-3">
      <div className="flex items-center gap-2 flex-wrap">
        {actions.map((action) => (
          <Button
            key={action.id}
            size="sm"
            variant="outline"
            className="text-xs gap-1.5"
            disabled={!!processing || !transcript.trim()}
            onClick={() => callPostProcess(action.id)}
          >
            {processing === action.id ? (
              <Loader2 className="w-3 h-3 animate-spin" />
            ) : (
              <action.icon className="w-3 h-3" />
            )}
            {action.label}
          </Button>
        ))}
        <Button
          size="sm"
          variant="outline"
          className="text-xs gap-1.5"
          disabled={!!processing || !transcript.trim()}
          onClick={() => setShowCustom(!showCustom)}
        >
          <MessageSquare className="w-3 h-3" /> Custom
        </Button>
        {onFinalReport && (
          <Button
            size="sm"
            variant={allSpeakersComplete ? "default" : "outline"}
            className="text-xs gap-1.5"
            disabled={!allSpeakersComplete || isFinalReportLoading}
            onClick={onFinalReport}
          >
            {isFinalReportLoading ? (
              <Loader2 className="w-3 h-3 animate-spin" />
            ) : (
              <ClipboardList className="w-3 h-3" />
            )}
            Final Report
          </Button>
        )}
      </div>

      {/* Translate target language selector */}
      <div className="flex items-center gap-2">
        <span className="text-[10px] font-medium text-muted-foreground uppercase tracking-wider">Translate to:</span>
        <Select value={targetLang} onValueChange={setTargetLang}>
          <SelectTrigger className="h-7 text-xs w-40"><SelectValue /></SelectTrigger>
          <SelectContent>
            {TARGET_LANGUAGES.map((lang) => (
              <SelectItem key={lang} value={lang} className="text-xs">{lang}</SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      {showCustom && (
        <div className="flex gap-2">
          <Input
            placeholder="Enter custom instruction…"
            value={customPrompt}
            onChange={(e) => setCustomPrompt(e.target.value)}
            className="h-8 text-xs flex-1"
          />
          <Button
            size="sm"
            className="text-xs"
            disabled={!!processing || !customPrompt.trim()}
            onClick={() => callPostProcess("custom", { customPrompt })}
          >
            {processing === "custom" ? <Loader2 className="w-3 h-3 animate-spin" /> : "Run"}
          </Button>
        </div>
      )}
    </div>
  );
}
