ALTER TABLE public.brand_kit 
  ADD COLUMN IF NOT EXISTS website TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS tagline TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS cta TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS target_audience TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS font_style TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS reference_aesthetic TEXT NOT NULL DEFAULT '';